"""Last cleaning

Revision ID: 8a0c6d940500
Revises: fc3f6d7bf51c
Create Date: 2025-06-15 18:14:28.904409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0c6d940500'
down_revision: Union[str, None] = 'fc3f6d7bf51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_cleaning_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_cleaning_time')
    # ### end Alembic commands ###
