"""num of coffee made

Revision ID: ecef8c04b7bc
Revises: 8a0c6d940500
Create Date: 2025-06-15 20:40:29.843102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecef8c04b7bc'
down_revision: Union[str, None] = '8a0c6d940500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('numbers_of_coffee', sa.Integer(), nullable=True))
    op.drop_column('sensors_data', 'numbers_of_coffee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors_data', sa.Column('numbers_of_coffee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('devices', 'numbers_of_coffee')
    # ### end Alembic commands ###
