"""Total active time

Revision ID: fc3f6d7bf51c
Revises: a37ddecba45d
Create Date: 2025-06-15 17:30:55.166606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3f6d7bf51c'
down_revision: Union[str, None] = 'a37ddecba45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('total_active_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'total_active_time')
    # ### end Alembic commands ###
